# Generated by Django 5.0.3 on 2024-03-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm_bg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedimage',
            name='image',
            field=models.ImageField(upload_to='images/receved/'),
        ),
        migrations.AlterField(
            model_name='processedimage',
            name='result_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/processed/'),
        ),
    ]
